create table advertisement (id bigint not null auto_increment, city varchar(32) not null, date_ofcreate datetime, description varchar(256), max_number_of_participants integer not null, min_number_of_participants integer not null, sport varchar(4) not null, street varchar(32) not null, url varchar(64), user_id bigint, primary key (id)) engine=MyISAM;
create table benefit_card (id bigint not null auto_increment, name_of_benefit_card varchar(255), primary key (id)) engine=MyISAM;
create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
create table message (id bigint not null auto_increment, date_ofcreate datetime, message varchar(255), sender varchar(255), user_id bigint, primary key (id)) engine=MyISAM;
create table participants (advertisement_id bigint not null, user_id bigint not null) engine=MyISAM;
create table time_of_game (id_time_of_game bigint not null auto_increment, date datetime, advertisement_id bigint, primary key (id_time_of_game)) engine=MyISAM;
create table user (id bigint not null auto_increment, password varchar(64) not null, username varchar(32) not null, user_detail_id bigint, primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, roles_id bigint not null, primary key (user_id, roles_id)) engine=MyISAM;
create table user_detail (id bigint not null auto_increment, birthday datetime, email varchar(255), gender varchar(255), phone varchar(255), primary key (id)) engine=MyISAM;
create table user_role (id bigint not null, description varchar(128), role varchar(32), primary key (id)) engine=MyISAM;
alter table advertisement add constraint FK6l68mvl7eypahv3tmaf7ndwie foreign key (user_id) references user (id);
alter table message add constraint FKb3y6etti1cfougkdr0qiiemgv foreign key (user_id) references user (id);
alter table participants add constraint FKlygocmohuh11svfduxxw8ykk6 foreign key (user_id) references user (id);
alter table participants add constraint FKqsnsk4e7vdhurdwss8a2jhksy foreign key (advertisement_id) references advertisement (id);
alter table time_of_game add constraint FKt8mvp0vldjo0pt59dpke9jf2u foreign key (advertisement_id) references advertisement (id);
alter table user add constraint FKda0fetw3e5nbo2brw8c0n9bts foreign key (user_detail_id) references user_detail (id);
alter table user_roles add constraint FK5i6gd32hnpr2nyf5edlvl9nhw foreign key (roles_id) references user_role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);