create table advertisement (id_advertisement bigint not null auto_increment, actual_number_of_participants integer not null, city varchar(32), date_ofcreate datetime, description varchar(512), max_number_of_participants integer not null, min_number_of_participants integer not null, sport varchar(4), street varchar(32), url varchar(64), user_id bigint, primary key (id_advertisement)) engine=MyISAM;
create table benefit_card (id bigint not null, name_of_benefit_card varchar(255), primary key (id)) engine=MyISAM;
create table hibernate_sequence (next_val bigint) engine=MyISAM;
insert into hibernate_sequence values ( 1 );
create table time_of_game (id_time_of_game bigint not null auto_increment, date datetime, advertisement_id bigint, primary key (id_time_of_game)) engine=MyISAM;
create table user (id bigint not null auto_increment, password varchar(64) not null, username varchar(32) not null, primary key (id)) engine=MyISAM;
create table user_roles (user_id bigint not null, roles_id bigint not null, primary key (user_id, roles_id)) engine=MyISAM;
create table user_role (id bigint not null, description varchar(128), role varchar(32), primary key (id)) engine=MyISAM;
alter table advertisement add constraint FK6l68mvl7eypahv3tmaf7ndwie foreign key (user_id) references user (id);
alter table time_of_game add constraint FKt8mvp0vldjo0pt59dpke9jf2u foreign key (advertisement_id) references advertisement (id_advertisement);
alter table user_roles add constraint FK5i6gd32hnpr2nyf5edlvl9nhw foreign key (roles_id) references user_role (id);
alter table user_roles add constraint FK55itppkw3i07do3h7qoclqd4k foreign key (user_id) references user (id);