version: '3.1'

services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: playtogether
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/lib/mysql